### ISSUE TITLE
IndexError: Line 271

### ISSUE THREAD

**Issue by sinaotl** [arvkevi/kneed#119]
Hi,
I believe we need a safeguard for falling outside of the bound in the **find_knee** function, Line 271. Since j=i+1, it can fall out the length of the array in certain cases!

to reproduce the error:
x = [0.34, 0.32, 0.30]
y = [1, 2, 6]
kn = KneeLocator(x, y, curve="convex", direction="decreasing")

**Comment by arvkevi** [comment]
Thanks for reporting the issue @sinaotl. In the next release, to find the knee, set `S=0.0`.
