### ISSUE TITLE
Knee is outside the x vector

### ISSUE THREAD

**Issue by ggautreau** [arvkevi/kneed#13]
Hi,

I run the following code:

```
from kneed import KneeLocator

kneedle = KneeLocator([3,4,5,6,7,8], [1.4699,1.4149,1.3868,1.3594,1.3411,1.3265], direction='decreasing',curve='convex')

print(kneedle.knee)
```
And the output of `kneedle.knee` is `0.0` without any errors throwed or printed despite that 0.0 is not included in x. Is it expected ?

Bye

**Comment by arvkevi** [comment]
Thanks @ggautreau, I'll have to look into that, looks like the threshold `kneedle.Tmx` is negative in this case, which is incorrect.

**Comment by ggautreau** [comment]
Ok, yes you can. Thank you.

**Comment by arvkevi** [comment]
see the [`neg_threshold`](https://github.com/arvkevi/kneed/pull/15) PR
