### ISSUE TITLE
How to use it with Multivariate X, Throwing interpolation axis Error

### ISSUE THREAD

**Issue by yug95** [arvkevi/kneed#131]
Hi Team, I am trying to use Knee locator package to get optimal number of features in my dataset. I have a X data frame whose shape is (100, 10) and Y data frame whose shape is (100, 1). Attached Screenshot. 

While applying same in Knee locator algorithm it throws error as - _"ValueError: x and y arrays must be equal in length along interpolation axis._"

I Also tried converting it into Numpy array and then used but same error.

![image](https://user-images.githubusercontent.com/13421129/192697327-c5673362-079c-4f0d-8036-cd63b0685858.png)
![image](https://user-images.githubusercontent.com/13421129/192697387-9aaa18c9-7477-4cb0-9598-68ba35f7167d.png)

**Comment by arvkevi** [comment]
Hi @yug95, kneed is designed to be used with two 1D arrays as input. This is not clear in the `KneeLocator` docstring, so I created a PR [here](https://github.com/arvkevi/kneed/pull/132). Does this additional information help answer your question? I can think of some ways to apply kneed to a DataFrame, but I'm not sure if that's what you want to use kneed to do.
