### ISSUE TITLE
Ability to change title, and set xlabel and ylabel for visualization function

### ISSUE THREAD

**Issue by Janson-L** [arvkevi/kneed#133]
I find this to be useful when I want to change the title and set xlabel ylabels of the visualization.

**Comment by arvkevi** [comment]
Thanks for the suggestion @Janson-L, I'll take a look at why the CI failed on the PR tonight.

**Comment by Janson-L** [comment]
Hmm, even after the CI update it still doesn't pass the codecov test, specifically line 324 where it complains the doc string is not covered inside the test. Do you think it could be caused by the hyphen for `X-axis` and `Y-axis` at the explanation string? @arvkevi

**Comment by arvkevi** [comment]
I bumped the coverage to 100% in #136 and rebased your PR, seems to have fixed the issue. Thanks for your contribution @Janson-L!
