### ISSUE TITLE
Remove unnecessary warning

### ISSUE THREAD

**Issue by dizcza** [arvkevi/kneed#149]
The following warning is unnecessary:
```
        if self.all_knees == set():
            warnings.warn("No knee/elbow found")
            return None, None
```
It's obvious from the output `if elbow is None` that no knees have been found. This warning yields no useful information and I vote for removing it.
Imagine how many warnings you'd get if scipy always warned about no solution found before outputting `None`s.
I can suppress this warning manually but it's cumbersome.

**Comment by arvkevi** [comment]
Thanks for the suggestion @dizcza. It makes sense to remove that line. Would you like to create a PR? If so, don't forget to remove [this test](https://github.com/arvkevi/kneed/blob/cff906a7c02a792da52940579b534f097c94e849/tests/test_sample.py#L292). Otherwise I can get to it later this week.

**Comment by dizcza** [comment]
Sure, I'll come up with a PR.
