### ISSUE TITLE
Change print output to warnings

### ISSUE THREAD

**Issue by kev494** [arvkevi/kneed#18]
Would it be possible to change the two prints in your code to [warnings](https://docs.python.org/3/library/warnings.html#module-warnings)? 
I am using your handy tool to calculate the optimal k for a recursive k-means clustering to create a top-down hierarchical clustering. Naturally there will be no optimal k at any point and then I would end the recursion. The repeated prints slow down the application quite a bit. With the warnings-module I could ignore those.

**Comment by arvkevi** [comment]
fixed by #19
