### ISSUE TITLE
find_knee() picks kneepoint from the wrong array

### ISSUE THREAD

**Issue by Peterdha** [arvkevi/kneed#27]
find_knee() finds the index of the knee point correctly, it also assignes the correct value from the normalized array `norm_knee_ = self.xsn[self.xmx_idx[mxmx_i]]`
but it selects the actual knee from the raw input data, while it should use the values from the evenly spaced array
currently: `knee_ = self.x[self.xmx_idx[mxmx_i]]`
should be:  `knee_ = self.Ds_x[self.xmx_idx[mxmx_i]]`

**Comment by arvkevi** [comment]
@Peterdha I'm going to close this for now only because I was getting strange results when selecting the knee from `Ds_x`. I only tinkered with it on a couple Saturday afternoons, If you want to investigate it more thoroughly with an example, we can re-open.
