### ISSUE TITLE
Non Negative Values in Y

### ISSUE THREAD

**Issue by raviolli** [arvkevi/kneed#4]
Is there a reason why if Y has no negative an error is returned.

```
>>> x = range(2,20)
>>> y=[]
>>> for i in x:
...     y.append(i*100)
>>> x
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
>>> y
[200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900]
>>> 
>>> kneed.KneeLocator(x,y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kneed/knee_locator.py", line 61, in __init__
    self.knee, self.norm_knee, self.knee_x = self.find_knee()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kneed/knee_locator.py", line 74, in find_knee
    mxmx_iter = np.arange(self.xmx_idx[0], len(self.xsn))
IndexError: index 0 is out of bounds for axis 0 with size 0

```
```
>>> y[0]=-1
>>> kneed.KneeLocator(x,y)
<kneed.knee_locator.KneeLocator object at 0x106a56d10>
```

**Comment by raviolli** [comment]
Hi arvkevi. I think the issue is not with the code... but rather the use I was doing it with. 

Since I think the code is trying to find the Knee rather then the elbow. 

but I found this:

> TypeError: __init__() got an unexpected keyword argument 'direction'

when trying to use kneed to find the optimal K

**Comment by raviolli** [comment]
Solution Solved. Update from github rather then pip default repo

**Comment by arvkevi** [comment]
OK, I think it also may have been due to the distance curve `xd, yd` not be polynomial in your example. This issue is still relevant, I'm going to update the code so it doesn't fail, rather it returns `None` and print a warning message.

**Comment by arvkevi** [comment]
Once I do that, I'll close this issue & update the package on PyPI

**Comment by arvkevi** [comment]
@raviolli the example you provided didn't have a local maximum, which caused the error. See the image below, b383b0b includes a print statement informing the user that no maxima was found and returns `None` for the knee so the user can inspect the function.

<img width="1109" alt="screen shot 2018-02-27 at 8 57 34 pm" src="https://user-images.githubusercontent.com/9151717/36765830-1f6ea2d2-1c01-11e8-8020-4887763c4cb6.png">
