### ISSUE TITLE
PyPI Release Current Update

### ISSUE THREAD

**Issue by jlevy44** [arvkevi/kneed#47]
Hi there,

For some reason the current updated package that you have on github is not the same as the one that is currently PyPI released. Could you please update it please so that I may add it to my install reqs? Thanks!

Awesome package.

**Comment by arvkevi** [comment]
Hi @jlevy44 I just pushed a new version to PyPI with the most recent source code, can you let me know if `pip install kneed` works for you?

**Comment by jlevy44** [comment]
Awesome, thanks so much. For some reason the knee estimate that I was getting with 0.2.6 was different than the latest repo (0.4.x) (the latter new ones is what I'm looking for, if there was some way to penalize towards earlier values that'd be great, some "weighted" knee, but the new results are perfect):

**Old:**
![image](https://user-images.githubusercontent.com/19698023/64926588-4e186580-d7cd-11e9-9157-604610e88844.png)
![image](https://user-images.githubusercontent.com/19698023/64926590-5670a080-d7cd-11e9-8772-cab133976ef6.png)

**New:**
![image](https://user-images.githubusercontent.com/19698023/64926600-70aa7e80-d7cd-11e9-957e-54512860bfd6.png)

![image](https://user-images.githubusercontent.com/19698023/64926595-67b9ad00-d7cd-11e9-9995-357268c2438f.png)

**Comment by arvkevi** [comment]
Hmm, both the *old* and *new* seem a bit off to me. Can you share the `x`, `y`?
I'm glad it's working for you though 😄

**Comment by arvkevi** [comment]
Hi, @jlevy44 do you mind if I close this thread? Seems like the new release resolved the issue you were having. Feel free to open a new issue regarding the elbow point in your graph, it seems off to me, but difficult to tell without the data.

Thanks

**Comment by jlevy44** [comment]
Sure, definitely another issue, thanks for pushing the update!
