### ISSUE TITLE
invert=True option buggy

### ISSUE THREAD

**Issue by ashwinvis** [arvkevi/kneed#5]
I get an error message like: `ValueError: too many values to unpack.` I think you meant a `;` but put a `,` instead in this line:

https://github.com/arvkevi/kneed/blob/master/kneed/knee_locator.py#L22

P.S.: Good job on this package!

**Comment by arvkevi** [comment]
Thanks @ashwinvis good catch! I added some conditions to make sure user input is sorted appropriately. Right now, it's entirely up to the user to know whether they are looking for a knee or elbow, maybe it should be more verbose when constructing a `KneeLocator` instance.

**Comment by arvkevi** [comment]
@ashwinvis feel free to reopen the issue or open a PR if this doesn't fix the problem :)
