### ISSUE TITLE
KneeLocator fails if there are flat extrema

### ISSUE THREAD

**Issue by tomas-teijeiro** [arvkevi/kneed#52]
This simple example fails:

```python
from kneed import KneeLocator
x = [0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0]
y = [1, 0.787701317715959, 0.7437774524158126, 0.6559297218155198, 0.5065885797950219, 0.36749633967789164, 0.2547584187408492, 0.16251830161054173, 0.10395314787701318, 0.06734992679355783, 0.043923865300146414, 0.027818448023426062, 0.01903367496339678, 0.013177159590043924, 0.010248901903367497, 0.007320644216691069, 0.005856515373352855, 0.004392386530014641]
k = KneeLocator(x, y, curve='convex', direction='decreasing')
```
Output:
`UserWarning: No knee/elbow found`

However, if we obtain the normalized knee plot, it is clear that there is a "flat optimum".

![knee](https://user-images.githubusercontent.com/4498106/69006397-0332df80-092f-11ea-96b3-4156ce026ea8.png)

It seems that the algorithm should be able to find that point between 0.4 and 0.5. 

I've been able to workaround this issue by modifying `knee_locator.py` in the calculation of `self.maxima_indices` and `self.minima_indices`, by using `np.greater_equal` and `np.less_equal` rather than `np.great` and `np.less`, but I'm not sure if this is a proper solution.

Thanks!

**Comment by arvkevi** [comment]
Thanks for posting the issue with an example @tomas-teijeiro, I'll take a look.

**Comment by arvkevi** [comment]
Great suggestion @tomas-teijeiro! See #53, using `np.greater_equal` and `np.less_equal` seems to address this, while also not breaking any of the other tests. It seems like this issue could be encountered frequently, so I'm going to push these changes to PyPI soon unless you can spot any potential errors.

```python
k = KneeLocator(x, y, curve='convex', direction='decreasing', S=0.0)
k.plot_knee_normalized();
```
![image](https://user-images.githubusercontent.com/9151717/69742833-6bda4300-110b-11ea-89e5-583515052169.png)

```python
k = KneeLocator(x, y, curve='convex', direction='decreasing', S=1.0)
k.plot_knee_normalized();
```
![image](https://user-images.githubusercontent.com/9151717/69742921-89a7a800-110b-11ea-8ce9-afa22feeb834.png)

**Comment by tomas-teijeiro** [comment]
Great! The only problem I can imagine with using `np.greater_equal` and `np.less_equal` is that if the difference curve has a staircase shape, then every step would be detected as a local maximum/minimum. However, since the algorithm selects the global one, I don't think it has any effect on the final result.

**Comment by arvkevi** [comment]
Agreed, that would be expected behavior, thanks again!
