### ISSUE TITLE
Addition of figsize param in plots ?

### ISSUE THREAD

**Issue by gperakis** [arvkevi/kneed#56]
Hello Kevin,

Great work with the algo and the plots. One thing that I would personally prefer, is to let the user define the figure size of the plots. 
What do you think?

Best, 
George

**Comment by arvkevi** [comment]
Hi @gperakis, thanks! 

The intention with the plots was just to show users how to interrogate the `KneeLocator` attributes. It's only a couple of lines of code to generate the plots once the `KneeLocator` object has been instantiated. So my hope is that users would make plots that suit their needs outside of `kneed`.

That being said, I like the idea of adding *some* flexibility with the output plots. A keyword argument could easily be added [here](https://github.com/arvkevi/kneed/blob/1458c7c625707e2a24738ec5694eef4f91f9c664/kneed/knee_locator.py#L217) like `def plot_knee(self, figsize=(6, 6)):`. That should be pretty harmless. I can get to this in the next day or so, but feel free to open a pull request if you'd like. 😄

**Comment by gperakis** [comment]
Hi @arvkevi ,
Sure, I'll open a pull request ASAP ! :) 
Thanks again!

**Comment by arvkevi** [comment]
fixed in #57 thank you, @gperakis 👍
