### ISSUE TITLE
Example graphs dont make sense

### ISSUE THREAD

**Issue by raviolli** [arvkevi/kneed#63]
Hi There, I may be wrong but it seems that the example graphs at the TOP of the readme 'convex' 'increasing' etc. don't make the examples below. It's quite confusing... :D 

Thanks, please fix. Love the repo.

**Comment by arvkevi** [comment]
Thanks for using the repo. Could you please identify a specific example that is confusing.

The normalized plots are all transformed to concave increasing for visualization, which could be the source of confusion. 

Under the Visualize section of the README:
**Note that all (x, y) are transformed for the normalized plots**

Does this clarify your concerns?
