### ISSUE TITLE
Problem with invert=True

### ISSUE THREAD

**Issue by e-271** [arvkevi/kneed#7]
Thanks for writing this library, it looks very useful.

I'm having trouble with the invert=True parameter in Python 3.5. It throws an error on line 22:
```
        if self.invert:
            self.original_x = self.x, self.original_y = self.y
```
so i changed it to:

```
        if self.invert:
            self.original_x, self.original_y = self.x, self.y
```

That works ,but then it throws an error on line 27:
```
        if not np.array_equal(np.array(self.x), np.sort(self.x)):
            raise ValueError('x values must be sorted')
```

My code is using walthrough.ipynb with data from the DataGenerator, and the only thing I changed is this line in [5]:
`kneedle = KneeLocator(x, y, S=1.0, invert=True)`

Do you have any suggestions for how to get it working?

**Comment by arvkevi** [comment]
Hi Esther, thanks for checking out the repository and opening this issue.

Did you install using `pip install kneed` or did you clone the source code from git?
My gut feeling is that you installed from `pip` which is outdated... 😞  

I need to update pypi. If you use the [Launch Binder button from the README](https://mybinder.org/v2/gh/arvkevi/kneed/master), you can play with the most current code.

I'll try to update pypi tonight, thanks again.

**Comment by arvkevi** [comment]
Try re-installing with pip, I bumped the version to `v.0.0.5`.
Can you please let me know if this fixes your issue.

**Comment by e-271** [comment]
Thanks for updating it. I did install with pip, I updated it and that fixed the issue.

**Comment by arvkevi** [comment]
Glad to hear it! Other updates to come soon, see #6 
If you clone the repo and switch to the [fix_increasing branch](https://github.com/arvkevi/kneed/tree/fix_increasing) I've started a solution for that issue.

**Comment by e-271** [comment]
Good to know, thanks! I'm trying this out on some radar data to determine parameters for DBSCAN, I'll let you know if I run in to any other problems.
