### ISSUE TITLE
What if there are multiple knee points?

### ISSUE THREAD

**Issue by shineisagoodgirl** [arvkevi/kneed#75]
Your algorithm helps me a lot，but can it only find one point at a time? What if there are multiple knee points？thank you
![knee points](https://github.com/shineisagoodgirl/problem/blob/master/46D0C0870FB875401C264270F992B6D0.JPG)

**Comment by arvkevi** [comment]
Hello @shineisagoodgirl, thanks for your question. There is a [unit test](https://github.com/arvkevi/kneed/blob/d7b75a184a86e4ac146acee09ed61d42554b048b/tests/test_sample.py#L151) that checks the knee points of a sine wave. The trick is that `direction` and `curve` need to be modified to detect different types of knees in one line. Kneed can't guess which curve is the one the user is trying to identify.

You could use the code from the unit test to help get you started:
```python
x = np.arange(0, 10, 0.1)
y_sin = np.sin(x)

sine_combos = [
    ('decreasing', 'convex'),
    ('increasing', 'convex'),
    ('increasing', 'concave'),
    ('decreasing', 'concave'),
]
expected_knees = [4.5, 4.9, 7.7, 1.8]
detected_knees = []
for direction, curve in sine_combos:
    kl_sine = KneeLocator(
        x, y_sin, direction=direction, curve=curve, S=1, online=True
    )
    detected_knees.append(kl_sine.knee)
assert np.isclose(expected_knees, detected_knees).all()
```

You could plot this:

```python
plt.style.use("fivethirtyeight")
plt.figure(figsize=(8, 8))
plt.plot(x, y_sin)
plt.vlines(
    detected_knees[0],
    min(y_sin),
    max(y_sin),
    linestyles="--",
    color="#fc4f30",
    label="convex decreasing",
)
plt.vlines(
    detected_knees[1],
    min(y_sin),
    max(y_sin),
    linestyles="--",
    color="#e5ae38",
    label="convex increasing",
)
plt.vlines(
    detected_knees[2],
    min(y_sin),
    max(y_sin),
    linestyles="--",
    color="#6d904f",
    label="concave increasing",
)
plt.vlines(
    detected_knees[3],
    min(y_sin),
    max(y_sin),
    linestyles="--",
    color="#8b8b8b",
    label="concave decreasing",
)
plt.legend()
```

![sine_knee](https://user-images.githubusercontent.com/9151717/82903888-a5133480-9f2f-11ea-8eaa-d1ed04bbdd49.png)

Notice that the concave increasing knee could be at **two** locations in the figure. If there is more than one potential knee point for a line, `kneed` can show you all the candidate knee points by accessing the attribute `.all_knees`.

```python
kl_sine = KneeLocator(
    x, y_sin, direction='increasing', curve='concave', S=1, online=True
)

print(kl_sine.all_knees)
{1.4000000000000001, 7.7}
```
