### ISSUE TITLE
kneed fails to find elbow point

### ISSUE THREAD

**Issue by Physics96** [arvkevi/kneed#77]
Hi,

I can not calculate the knee point of the following dataset:

`x =[7.58664459e-05, 1.11978460e-04, 2.38899123e-04, 4.90114492e-04,
       7.82853340e-04, 1.02036258e-03, 1.31875021e-03, 2.30043176e-03,
       4.40276718e-03, 7.70743315e-03, 1.60477105e-02, 3.83262376e-02] `
`y =[0.27655736, 0.27249274, 0.2646699 , 0.25457005, 0.248055  ,
       0.2457939 , 0.24485397, 0.24355771, 0.24200204, 0.24073301,
       0.23906376, 0.23606901] `
![Figure_1](https://user-images.githubusercontent.com/67896774/86571606-f7556580-bf71-11ea-8834-536909839efe.png)

The kneed algorithm always chooses the first datapoint, which is obviously not the elbow point.

Thanks

**Comment by arvkevi** [comment]
Thank you for checking out the repo and reporting the issue. I think I've got a bug and I haven't had time to fix it recently. The solution wasn't immediately obvious after looking into it for a few minutes, so I'll need to find a night where I can debug.

**Comment by arvkevi** [comment]
Thanks, @Physics96 for reporting the bug. I pushed a working [branch](https://github.com/arvkevi/kneed/tree/refactor) and have an [open PR](https://github.com/arvkevi/kneed/pull/80) that should fix this issue. If you want to check out the branch and test it, let me know how it goes. I'm going to wait a couple days to merge the PR and cut a new release.

```python
x = [7.58664459e-05, 1.11978460e-04, 2.38899123e-04, 4.90114492e-04, 7.82853340e-04, 1.02036258e-03, 1.31875021e-03,
     2.30043176e-03, 4.40276718e-03, 7.70743315e-03, 1.60477105e-02, 3.83262376e-02]
y = [0.27655736, 0.27249274, 0.2646699, 0.25457005, 0.248055, 0.2457939, 0.24485397, 0.24355771, 0.24200204,
     0.24073301, 0.23906376, 0.23606901]
kl = KneeLocator(
    x,
    y,
    curve="convex",
    direction="decreasing",
)
```

```python
kl.plot_knee()
```
![download](https://user-images.githubusercontent.com/9151717/88446942-3f8ed780-cdfc-11ea-83c1-1d4a54c178a5.png)

```python
kl.plot_knee_normalized()
```
![download (1)](https://user-images.githubusercontent.com/9151717/88446944-4584b880-cdfc-11ea-9e1b-9d6c838f6ac4.png)

**Comment by Physics96** [comment]
Hi, seems to be working fine now - thanks. Could not find any issues.

**Comment by arvkevi** [comment]
Glad it's working now, thanks again for posting the issue.
