### ISSUE TITLE
How to find value corresponding to "knee point " on  y axis?

### ISSUE THREAD

**Issue by Emenent758** [arvkevi/kneed#78]
Hy !
its working great in my case.But I want to find value on y axes corresponding to knee point on x-axis.Is there any way to do it?
Because currently when I print kn.knee it gives me value on x-axis.

Thanks

**Comment by Physics96** [comment]
If I understand you correctly, you just want to get the y-coordinate of the calculated knee-point.

This can be programmed in a very simple way: Just extract the component y-data vector, which belongs to the found x-coordinate. I often use the 'numpy.where' function, which comes with the numpy package.

`y_knee = y_data[numpy.where(x_data == x_knee)[0]]`

'x_knee' is the calculated x-value of the knee-point.

**Comment by arvkevi** [comment]
Hi @Emenent758, thanks for using kneed. The value on the y-axis at the knee point is stored in the `.knee_y` and `.elbow_y` attributes. The normalized y-axis values are stored in `.norm_knee_y` and `.norm_elbow_y`. The second code block in [this section](https://github.com/arvkevi/kneed#find-knee) of the README shows an example.

Does this answer your question?

**Comment by Emenent758** [comment]
Thank you very much (y)
