### ISSUE TITLE
Problem with curves with multiple slopes

### ISSUE THREAD

**Issue by tonitonae** [arvkevi/kneed#84]
Hi.

First of all, thanks for developing this software. I find it quite interesting and useful for multiple purposes.

I am trying to use it on some data that I have obtained after processing a surface in which I detect local optima (in the z axis). Due to the acquisition process, there are many noise points at the floor level which I want to remove and I thought that a good approach would be to plot a distance plot and cut at the elbow. This manually works, but I wanted to automate the process and that was when I found kneed.

However, in my plot there are changes in the slope of the curve, as shown below. What I want it to do is to cut at the clearly pronounced elbow (around x=500) to remove all the points with an almost equal height. However, the knee point returned by kneed is one at the very beginning of the plot (x=26).

Any suggestions on how to tackle this?

I attach two pictures: one of the elbow plot and the one obtained with the plot_knee_normalized method.

Thanks in advance for your help.

Regards.

![index](https://user-images.githubusercontent.com/71767032/94011288-6d19e200-fda7-11ea-93e0-53f18e8e3657.png) ![index2](https://user-images.githubusercontent.com/71767032/94011302-71de9600-fda7-11ea-8bc3-869a9ec9d93b.png)

**Comment by arvkevi** [comment]
Hi @tonitonae, thanks for checking out the repo. The algorithm is sensitive to the number of points in the input arrays. Try increasing the value of the `S` parameter of the `KneeLocator`. It represents the minimum number of points below the local distance maxima before calling a knee point. More info and an example of using `S` are in the [docs](https://kneed.readthedocs.io/en/stable/parameters.html#s).

Let me know if this helps!

**Comment by tonitonae** [comment]
Yep!

Thanks for the quick reply. With a S  value of 3 it works like a charm!

![plot](https://user-images.githubusercontent.com/71767032/94026962-a445be80-fdba-11ea-9271-702642d39436.png)

Thanks again and sorry for opening an issue before digging in the docs. Hope this helps someone else!

Cheers!

**Comment by arvkevi** [comment]
Glad to hear it @tonitonae 😄
